// Code generated by Slice Machine. DO NOT EDIT.

import AboutContent from './AboutContent';
import Footer from './Footer';
import Hero from './Hero';
import Nav from './Nav';
import SendMessage from './SendMessage';
import StoriesList from './StoriesList';

export { AboutContent, Footer, Hero, Nav, SendMessage, StoriesList };

export const components = {
    about_content: AboutContent,
    footer: Footer,
    hero: Hero,
    nav: Nav,
    send_message: SendMessage,
    stories_list: StoriesList,
};
