// Code generated by Slice Machine. DO NOT EDIT.

import Footer from './Footer';
import Hero from './Hero';
import Nav from './Nav';
import StoriesList from './StoriesList';

export {
	Footer,
	Hero,
	Nav,
	StoriesList,
};

export const components = {
	footer: Footer,
	hero: Hero,
	nav: Nav,
	stories_list: StoriesList,
};
